### ISSUE TITLE
move steam + epic extraction into extract folder

### ISSUE THREAD

**Issue by shindym** [hhm970/c10-games-tracker-project#86]
## Description
- move `extract_epic.py`, `test_epic.py`, `steam_extract.py`,`conftest.py` and `test_steam.py` into the `extract` directory.

## Required Files
- `extract_epic.py`, `test_epic.py`, `steam_extract.py`, `conftest.py` and `test_steam.py`

## User Story
As an Engineer it is important that all the extract scripts are housed together to ensure that the repo is neat, easy to navigate and understand

**Comment by hhm970** [comment]
Just recently had a thought; since each extract script we're using for our respective gaming websites will have their functionality deployed into individual Lambdas, and thus will need individual Dockerfiles, would it be more effective to separate these extract scripts into individual folders?

One possible way to do this (possibly the way that would be most straightforward) would be to organise it like this,

```
pipeline/extract/steam/extract_steam.py
pipeline/extract/epic/extract_epic.py
pipeline/extract/gog/extract_gog.py
```

**Comment by shindym** [comment]
@hhm970 Didn't take this into consideration. Good proposed solution!
